name: 11ty Build
on: workflow_dispatch
jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
