name: garance referentiel
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Get all resources
      - uses: actions/checkout@v3
        with:
          repository: ArchivesNationalesFR/Referentiels
          path: Referentiels
          ref: version_2

      - name: test
        run: |
          pwd Referentiels
          ls -l /home/runner/work/garance/garance/Referentiels
      
      # Python
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/python/requirements.txt
      - name: Convert
        run: |
          python scripts/python/convertToJson.py --generate READ --input /home/runner/work/_temp/85d03958-5ffd-4a51-8f6f-0d89287107c9 --context src/_data/context.json --output src/_data/garance_python.json
