name: garance referentiel
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Get all resources
      - uses: actions/checkout@v3
        with:
          repository: ArchivesNationalesFR/Referentiels
          path: Referentiels
          ref: version_2

      - name: test
        run: ls -l Referentiels
          
      # Step 1 - convert to JSON
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r scripts/python/requirements.txt

      - name: Convert to JSON
        run: python scripts/python/convertToJson.py --generate READ --input /home/runner/work/ArchivesNationalesFR/Referentiels/version_2 --context src/_data/context.json --output garancePython.json
